

target 'PartidoProject' do
  use_frameworks!
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'IQKeyboardManagerSwift','7.1.1'
  pod 'Kingfisher'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'FSPagerView'
  pod 'AAINetwork', :http => 'https://prod-guardian-cv.oss-ap-southeast-5.aliyuncs.com/sdk/iOS-libraries/AAINetwork/AAINetwork-V1.0.0.tar.bz2', type: :tbz
  pod 'AAILiveness', :http => 'https://prod-guardian-cv.oss-ap-southeast-5.aliyuncs.com/sdk/iOS-liveness-detection/2.0.6/iOS-Liveness-SDK-V2.0.6.tar.bz2', type: :tbz
  pod 'KeychainAccess'
  pod 'KeenCodeUnit'
  pod 'Toast-Swift', '~> 5.1.1'
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
