//
//  PPConfuseHeader.h
// FIexiLend
//
//  Created by jacky on 2024/10/31.
//

#ifndef PPConfuseHeader_h
#define PPConfuseHeader_h

#define p_code              @"rsstratificationCiopjko"
#define p_message           @"rscascalhoCiopjko"
#define p_data              @"rsnyuCiopjko"
#define p_item              @"rsmusclyCiopjko"
#define p_token             @"rsrubicundityCiopjko"
#define p_sessionid         @"rscinematographCiopjko"
#define p_appstore          @"rsarillusCiopjko"
#define p_time              @"rshaeresCiopjko"
#define p_id                @"rsbarologyCiopjko"
#define p_name              @"rspreterminalCiopjko"
#define p_relation          @"rstarrianceCiopjko"
#define p_icon              @"rsmirrnyongCiopjko"
#define p_list              @"rssliceCiopjko"
#define p_type              @"rskuskokwimCiopjko"
#define p_url               @"rseltCiopjko"
#define p_product_id        @"rsstarrinessCiopjko"
#define p_title             @"rslangurCiopjko"
#define p_subtitle          @"rsullageCiopjko"
#define p_sub_title         @"sub_title"
#define p_imgUrl            @"rsmceCiopjko"
#define p_imgUrlNew         @"rstheosophistCiopjko"
#define p_productLogo       @"rstiptiltCiopjko"
#define p_amountRange       @"rsveronalCiopjko"
#define p_amountRangeDes    @"rscoiCiopjko"
#define p_productDesc       @"rsstroamCiopjko"
#define p_termInfo          @"rslappCiopjko"
#define p_termInfoDes       @"rsmaduraiCiopjko"
#define p_loanRate          @"rsflaccidCiopjko"
#define p_loanRateDes       @"rsimpresaCiopjko"
#define p_buttoncolor       @"rsveeCiopjko"
#define p_username          @"rsincinerationCiopjko"
#define p_smsCode           @"rspumpmanCiopjko"
#define p_phone             @"rseremicCiopjko"
#define p_siouanMc          @"siouanMc"
#define p_point             @"point"//??
#define p_uid               @"licensedMc"
#define p_realname          @"semisacredMc"
#define p_nextStep          @"rsreassemblyCiopjko"
#define p_step              @"rslangurCiopjko"
#define p_BANNER            @"NIMKS"
#define p_LARGE_CARD        @"NIMKKA"
#define p_SMALL_CARD        @"NIQQQA"
#define p_PRODUCT_LIST      @"NIQQQB"
#define p_RIDING_LANTERN    @"NIIUDS"
#define p_REPAY             @"NIQQQC"
#define p_enum              @"NIQQQJ"
#define p_txt               @"NIQQQK"
#define p_option            @"NIQQAA"
#define p_day               @"NIQQBB"

#define p_term_type         @"psychologueMc"
#define p_verify            @"expectantlyMc"
#define p_extendLists       @"rscredulousnessCiopjko"
#define p_repayment_order   @"rswelterCiopjko"
#define p_memberUrl         @"oilholeMc"
#define p_key               @"rsfractalCiopjko"
#define p_mobile            @"rssetwallCiopjko"
#define p_field             @"rsseditiouslyCiopjko"
#define p_filled            @"rschitterCiopjko"
#define p_items             @"rsliverwortCiopjko"
#define p_card_first        @"rszymogenCiopjko"
#define p_card_two          @"rsmerrimentCiopjko"
#define p_card_title        @"rsproblemCiopjko"
#define p_card_bg           @"rsgeosphereCiopjko"
#define p_card_type         @"rsrebosoCiopjko"
#define p_channel           @"rscurdleCiopjko"
#define p_account           @"rssdrsCiopjko"
#define p_relation_id       @"rsmortifyingCiopjko"
#define p_ocr_relation_id   @"rsdecagonalCiopjko"
#define p_liveness_r_id     @"rsattaintCiopjko"
#define p_wallet            @"rstoulouseCiopjko"
#define p_bank              @"rswaughianCiopjko"
#define p_countdown         @"rsmultangularCiopjko"
#define p_cate              @"rsfeasibilityCiopjko"
#define p_value             @"rstryptophanCiopjko"
#define p_license           @"rspastoraleCiopjko"
#define p_id_type           @"rsbailieCiopjko"
#define p_inputType         @"rsboringCiopjko"
#define p_optional          @"rstatpurushaCiopjko"
#define p_note              @"rsclemencyCiopjko"
#define p_order_no          @"velskoenMc"
#define p_orderNo           @"rsstingrayCiopjko"
#define p_productDetail     @"rstwitchCiopjko"
#define p_amount            @"rsferlieCiopjko"
#define p_date              @"rsepauletteCiopjko"
#define p_amountDesc        @"puppetryMc"
#define p_cityList          @"crown_now"
#define p_emergent          @"vocabularMc"
#define p_orderType         @"rsenglanderCiopjko"
#define p_pageNum           @"rsitoCiopjko"
#define p_pageSize          @"rsregsCiopjko"
#define p_orderId           @"odontophorousMc"
#define p_productId         @"efficacityMc"
#define p_productName       @"rsnorthwardCiopjko"
#define p_product_name      @"rscomitragedyCiopjko"
#define p_orderStatus       @"eparterialMc"
#define p_buttonText        @"rsemmanuelCiopjko"
#define p_orderStatusDesc   @"rscarabaoCiopjko"
#define p_orderStatusColor  @"rscartoonCiopjko"
#define p_buttonBgColor     @"rsanthropometristCiopjko"
#define p_orderAmount       @"rsjudeCiopjko"
#define p_loanDetailUrl     @"rsdistortiveCiopjko"
#define p_repayTime         @"rsbondCiopjko"
#define p_term              @"backtrackMc"
#define p_admin_area        @"rstellurionCiopjko"
#define p_country_code      @"rshistoidCiopjko"
#define p_country_name      @"rsregimeCiopjko"
#define p_feature_name      @"rstchadCiopjko"
#define p_longitude         @"rssplodgyCiopjko"
#define p_latitude          @"rsestroneCiopjko"
#define p_locality          @"rsantiresonanceCiopjko"
#define p_sub_admin_area    @"rsmonikerCiopjko"
#define p_idfa              @"noisefulMc"
#define p_idfv              @"climeMc"
#define p_afKey             @"gambianMc"
#define p_appid             @"appid"
#define p_start_time        @"crinumMc"
#define p_end_time          @"atheismMc"
#define p_sceneType         @"senileMc"
#define p_device_no         @"entrustMc"
#define p_is_huoti          @"direfulMc"
#define p_liveness_id       @"rscantalCiopjko"


#endif /* PPConfuseHeader_h */
